# Generated by Django 3.2.13 on 2022-06-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medshop', '0005_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='medshop.branch'),
            preserve_default=False,
        ),
    ]
